version: '3'

services:
    webapp:
        container_name: app
        build: .
        ports:
         - 5000:5000
    redis:
        image: redis:alpine

    nginxserver:
        container_name: nginxserver
        image: nginx:alpine
        ports: 
         - 8080:80
        volumes:
         - ~/nginx:/usr/share/nginx/html

    nginxproxy:
        container_name: nginxproxy
        image: nginx:alpine
        depends_on:
         - webapp  
         - redis
         - nginxserver
        ports:
         - 80:80
        volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
